### ISSUE TITLE
Finish HandStrength's __toString() function

### ISSUE THREAD

**Issue by kingarthurpt** [kingarthurpt/PHPPokerAlho#2]
Choose the best 5 cards of a CardCollection of 7 and implement a complete __toString function that can identify any HandStrength

**Comment by FDiniz14** [comment]
The implementation is completed on **feature/HandStrengthEval**, but there is a problem determining its ranking (Straight Flush and Royal Flush).

**Comment by kingarthurpt** [comment]
Done in d5deb1a1f98976d5d3c027051b7cc807c894cc3c https://github.com/kingarthurpt/PHPPokerAlho/pull/6
